name: Parse Submission

on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RBD_GITHUB_TOKEN }}

      - name: Check commit message
        id: check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == "Update repository stars" || "$COMMIT_MESSAGE" == "Update app info" ]]; then
            echo "skip=true" >> $GITHUB_ENV
            echo "::set-output name=skip::true"
          else
            echo "skip=false" >> $GITHUB_ENV
            echo "::set-output name=skip::false"
          fi

  update-app-info:
    if: needs.check-commit-message.outputs.skip == 'false'
    runs-on: ubuntu-latest
    needs: check-commit-message
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RBD_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node parse-app-info.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update app info"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.RBD_GITHUB_TOKEN }}

  update-stats:
    if: needs.check-commit-message.outputs.skip == 'false'
    runs-on: ubuntu-latest
    needs: update-app-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository stats
        id: get_stats
        run: |
          # Add your script to get repository stats here
