name: Update App Info

on:
  push:
    branches:
      - main

jobs:
  update-app-info:
    if: "!contains(github.event.head_commit.message, 'Update app info')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.RBD_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd shipixen && npm install

      - name: Run update script
        run: cd shipixen/scripts && node parse-app-info.js

      - name: Commit and push changes
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.RBD_GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update app info'
          git push https://x-access-token:${{ secrets.RBD_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

  output-number-of-changes:
    runs-on: ubuntu-latest
    needs: update-app-info
    steps:
      - name: Count number of changes
        run: |
          git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          git diff --name-only origin/main
