name: Update App Info

on:
  push:
    branches:
      - main

jobs:
  update-app-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Navigate to root directory
        run: cd shipixen

      - name: Install dependencies
        run: npm install

      - name: Navigate to scripts directory
        run: cd scripts

      - name: Run update script
        run: node parse-app-info.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update app info'
          git push
